/**
 * Auto-detects the deployment path for GitHub Pages.
 *
 * GitHub Pages serves project sites from /<repo>/ and user sites from /, and a
 * static host does no URL rewriting. The build must therefore bake the prefix
 * into every asset URL, or a project site 404s on /_next/*.css and renders
 * unstyled. Rather than relying on a hand-set environment variable, this reads
 * the git remote and derives the path automatically.
 *
 * Precedence:
 *   1. NEXT_PUBLIC_BASE_PATH (explicit override)
 *   2. the repository path derived from the git remote
 *   3. root (user/organisation site)
 *
 * Run before `next build`, since next.config.ts reads the result.
 */
import { execSync } from "node:child_process";
import { existsSync, writeFileSync } from "node:fs";
import path from "node:path";

const envPath = path.join(process.cwd(), ".env.local");
const explicit = process.env.NEXT_PUBLIC_BASE_PATH;

function readGitRemote() {
  if (!existsSync(path.join(process.cwd(), ".git"))) return null;
  try {
    return execSync("git remote get-url origin", {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
  } catch {
    return null;
  }
}

function parseRemote(remote) {
  if (!remote) return null;

  // Supports both SSH (git@github.com:owner/repo.git) and HTTPS
  // (https://github.com/owner/repo.git) remotes, and GitHub Enterprise hosts.
  const match =
    /github\.com[:/]([^/]+)\/([^/\s]+?)(?:\.git)?\/?$/i.exec(remote);
  if (!match) return null;

  const owner = match[1];
  const repo = match[2];

  // owner.github.io is a user/organisation site: served from the root.
  if (owner.toLowerCase().endsWith(".github.io")) {
    return { basePath: "", siteUrl: `https://${owner.toLowerCase()}` };
  }

  // owner.github.com/repo is the legacy subdomain form, also root-served.
  if (owner.toLowerCase().endsWith(".github.com")) {
    return { basePath: "", siteUrl: `https://${owner.toLowerCase()}` };
  }

  return {
    basePath: `/${repo}`,
    siteUrl: `https://${owner.toLowerCase()}.github.io`,
  };
}

const source = explicit ? "environment" : "git remote";
const detected = parseRemote(readGitRemote()) ?? { basePath: "", siteUrl: "" };

const basePath = explicit ?? detected.basePath;

// Keep the production domain as the canonical origin unless the remote points
// somewhere else, so canonical/OG/sitemap URLs match where the site is served.
const siteUrl =
  process.env.NEXT_PUBLIC_SITE_URL ?? detected.siteUrl ?? "";

const contents = [
  "# Generated by scripts/prepare-deploy.mjs. Do not edit by hand.",
  `# Deployment settings detected from ${source}.`,
  `NEXT_PUBLIC_BASE_PATH=${basePath}`,
  `NEXT_PUBLIC_SITE_URL=${siteUrl}`,
  "",
].join("\n");

writeFileSync(envPath, contents, "utf8");

console.log(
  [
    `prepare-deploy (${source}):`,
    `  base path: ${basePath ? `${basePath}/` : "/ (domain root)"}`,
    `  site url:  ${siteUrl || "https://parsispress.com (default)"}`,
  ].join("\n"),
);