/**
 * Resolves the deployment path and canonical origin for the static export.
 *
 * GitHub Pages does no URL rewriting: a project site at user.github.io/repo
 * 404s on every /_next/*.css unless the build bakes in the path. This derives
 * both values from the git remote so no manual configuration is needed.
 *
 * Precedence:
 *   base path — NEXT_PUBLIC_BASE_PATH, then the remote, then root
 *   site url  — NEXT_PUBLIC_SITE_URL, then the remote, then parsispress.com
 *
 * Note: these checks must use `||`, not `??`. GitHub Actions passes unset
 * repository variables through as empty strings, and `??` treats "" as a real
 * value — which produced NEXT_PUBLIC_SITE_URL= and an ERR_INVALID_URL at build.
 *
 * Run before `next build`, since next.config.ts reads the result.
 */
import { execSync } from "node:child_process";
import { existsSync, writeFileSync } from "node:fs";
import path from "node:path";

const envPath = path.join(process.cwd(), ".env.local");

/** Treats unset and empty-string env vars the same, unlike `??`. */
function fromEnv(value) {
  return value && value.trim() ? value.trim() : null;
}

function readGitRemote() {
  if (!existsSync(path.join(process.cwd(), ".git"))) return null;
  try {
    return execSync("git remote get-url origin", {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
  } catch {
    return null;
  }
}

function parseRemote(remote) {
  if (!remote) return null;

  // Supports SSH (git@github.com:owner/repo.git) and HTTPS
  // (https://github.com/owner/repo.git) remotes, and GitHub Enterprise hosts.
  const match = /github\.com[:/]([^/]+)\/([^/\s]+?)(?:\.git)?\/?$/i.exec(remote);
  if (!match) return null;

  const owner = match[1].toLowerCase();
  const repo = match[2];

  // owner.github.io and owner.github.com are user/organisation sites, which
  // Pages serves from the domain root.
  if (owner.endsWith(".github.io") || owner.endsWith(".github.com")) {
    return { basePath: "", siteUrl: `https://${owner}` };
  }

  return {
    basePath: `/${repo}`,
    siteUrl: `https://${owner}.github.io`,
  };
}

const remote = readGitRemote();
const detected = parseRemote(remote) ?? { basePath: "", siteUrl: "" };

const explicitBasePath = fromEnv(process.env.NEXT_PUBLIC_BASE_PATH);
const explicitSiteUrl = fromEnv(process.env.NEXT_PUBLIC_SITE_URL);

const basePath = explicitBasePath ?? detected.basePath;
const siteUrl = explicitSiteUrl || detected.siteUrl || "https://parsispress.com";

const contents = [
  "# Generated by scripts/prepare-deploy.mjs. Do not edit by hand.",
  `# Deployment settings${remote ? " detected from the git remote" : ""}.`,
  `NEXT_PUBLIC_BASE_PATH=${basePath}`,
  `NEXT_PUBLIC_SITE_URL=${siteUrl}`,
  "",
].join("\n");

writeFileSync(envPath, contents, "utf8");

console.log(
  [
    "prepare-deploy:",
    `  base path: ${basePath ? `${basePath}/` : "/ (domain root)"}`,
    `  site url:  ${siteUrl}`,
  ].join("\n"),
);